const data = [
  {
    date: "2022-03-16T15:01:57.999Z",
    ressourceCode: "E000-T002-U-FR",
    ressourceTitle: "Le Chaudron",
    new: true,
    poster_link: "https://dev.massatrails.net/media/img/chaudron.webp",
    metadata: {
      seasonNumber: 1,
      seasonsTotal: 1,
      episodeTotal: 7,
      voices: "Sabine",
      author: "SA - SL",
      keywords: [
        "Confidence",
        "Burnout",
        "Emotion",
        "Consentement",
        "Dire Non",
        "Manipulation",
        "Imposer",
        "Consentement",
        "Douter",
        "Parent",
        "Relation",
        "Complexe",
        "Pause",
        "Corps",
        "Rituel",
      ],
      language: "fr_FR",
      srt: false,
      description:
        "Venez cuire vos croyances limitantes dans ce chaudron magique. 7 phases de cuisson pour transformer ces croyances en puissantes ressources pour vivre « votre vrai VOUS »",
      introduction: "Le chaudron des croyances",
    },
  },
  {
    date: "2022-03-16T15:01:57.999Z",
    ressourceCode: "E000-T001-U-FR",
    ressourceTitle: "Confiance en Soi",
    new: true,
    poster_link: "https://dev.massatrails.net/media/img/HeroFirst.webp",
    metadata: {
      seasonsTotal: 6,
      episodeTotal: 30,
      voices: "MGarrett",
      author: "SA - SL",
      keywords: [
        "Confidence",
        "Burnout",
        "Emotion",
        "Consentement",
        "Dire Non",
        "Manipulation",
        "Imposer",
        "Consentement",
        "Douter",
        "Parent",
        "Relation",
        "Complexe",
        "Pause",
        "Corps",
        "Rituel",
      ],
      language: "fr_FR",
      srt: false,
      description:
        "Densifiez votre être. Découvrez le secret des Grenouilles, Jouez aux échecs, Rencontrez le fantôme, Admirez la beauté d’une Jarre, Sortez de votre cocon et Prenez votre envol.",
      introduction: "Confiance en soi : la recette de l’abondance",
    },
  },
  {
    date: "2022-03-16T15:01:57.999Z",
    ressourceCode: "E000-T003-S1-E1-U-FR",
    ressourceTitle: "Trouvez votre poids idéal",
    new: true,
    poster_link: "https://dev.massatrails.net/media/img/HeroEighth.webp",
    metadata: {
      seasonsTotal: 0,
      episodeTotal: 0,
      voices: "",
      author: "",
      keywords: [
        "Confidence",
        "Burnout",
        "Emotion",
        "Consentement",
        "Dire Non",
        "Manipulation",
        "Imposer",
        "Consentement",
        "Douter",
        "Parent",
        "Relation",
        "Complexe",
        "Pause",
        "Corps",
        "Rituel",
      ],
      language: "fr_FR",
      srt: false,
      description:
        "Vous avez tout essayé ? La solution est ailleurs. Venez découvrir votre poids idéal, contre toute logique !",
      introduction: "Trouvez votre poids idéal",
    },
    comingSoon: true,
  },
  {
    date: "2022-03-16T15:01:57.999Z",
    ressourceCode: "E000-T005-S1-E1-U-FR",
    ressourceTitle: "Intelligence Émotionnelle",
    new: true,
    poster_link: "https://dev.massatrails.net/media/img/HeroThird.webp",
    metadata: {
      seasonsTotal: 0,
      episodeTotal: 0,
      voices: "",
      author: "",
      keywords: [
        "Confidence",
        "Burnout",
        "Emotion",
        "Consentement",
        "Dire Non",
        "Manipulation",
        "Imposer",
        "Consentement",
        "Douter",
        "Parent",
        "Relation",
        "Complexe",
        "Pause",
        "Corps",
        "Rituel",
      ],
      language: "fr_FR",
      srt: false,
      description:
        "Les émotions sont notre GPS intérieur. Voyagez dans ces mondes fantastiques. Faites de vos émotions de solides alliés. Vous ne les vivrez plus jamais de la même façon.",
      introduction: "L’intelligence émotionnelle : notre force intérieure",
    },
    comingSoon: true,
  },
  {
    date: "2022-03-16T15:01:57.999Z",
    ressourceCode: "E000-T004-S1-E1-U-FR",
    ressourceTitle: "Stress",
    new: true,
    poster_link: "https://dev.massatrails.net/media/img/HeroSecond.webp",
    metadata: {
      seasonsTotal: 0,
      episodeTotal: 0,
      voices: "",
      author: "",
      keywords: [
        "Confidence",
        "Burnout",
        "Emotion",
        "Consentement",
        "Dire Non",
        "Manipulation",
        "Imposer",
        "Consentement",
        "Douter",
        "Parent",
        "Relation",
        "Complexe",
        "Pause",
        "Corps",
        "Rituel",
      ],
      language: "fr_FR",
      srt: false,
      description:
        "Calmer le stress, pourquoi pas ? Transformer le stress, c’est mieux. Rejoignez-nous : Jouez le Pompier, Sautez de la marmite, Devenez le poisson Arc-en-ciel…",
      introduction: "Stress ou calme intérieur ?",
    },
    comingSoon: true,
  },
  {
    date: "2022-03-16T15:01:57.999Z",
    ressourceCode: "E000-T006-S1-E1-U-FR",
    ressourceTitle: "Sommeil",
    new: true,
    poster_link: "https://dev.massatrails.net/media/img/HeroFourth.webp",
    metadata: {
      seasonsTotal: 0,
      episodeTotal: 0,
      voices: "",
      author: "",
      keywords: [
        "Confidence",
        "Burnout",
        "Emotion",
        "Consentement",
        "Dire Non",
        "Manipulation",
        "Imposer",
        "Consentement",
        "Douter",
        "Parent",
        "Relation",
        "Complexe",
        "Pause",
        "Corps",
        "Rituel",
      ],
      language: "fr_FR",
      srt: false,
      description:
        "Le sommeil, un ressort essentiel à la vie ? C’est justement cela qui vous stresse ? Faites le chat, et découvrez le plaisir d’un sommeil équilibré. ",
      introduction: "Equilibrez votre sommeil",
    },
    comingSoon: true,
  },
];

export default data;
